name: Frederik Wallner
favicon: null
layout_spectrum: 0.40843
typography_spectrum: 0.31324
title: Frederik Wallner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dad3c2'
    - '#02131e'
    - '#d39c7a'
    - '#a5432b'
    - '#57291d'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
